//
//  AppIconArtwork.swift
//  Peakmon
//
//  SwiftUI rendition of the Peakmon app icon for in-app display
//  (Settings → About header, etc.). The actual `.png` files in
//  `AppIcon.appiconset` are generated by `Tools/generate_icons.swift`
//  using Core Graphics; this SwiftUI view mirrors that artwork so
//  the in-app preview matches what the user sees in Finder/Dock.
//
//  Visual recipe (matches Tools/generate_icons.swift):
//    1. Squircle clip (corner radius = side × 0.2237).
//    2. Diagonal blue → purple gradient (#4A6BFF → #B14AFF).
//    3. Subtle white top highlight (alpha 0.18 → 0, vertical).
//    4. White `gauge.medium` SF Symbol, semibold, centred at ~62%
//       of the side length, soft drop shadow underneath.
//
//  The view scales relative to whatever frame the caller supplies
//  (typically 64 – 256 pt for in-app use). Apply `.frame(width:height:)`
//  on the caller side to size it.
//

import SwiftUI

struct AppIconArtwork: View {
    /// Reference canvas side used by the rasteriser. Kept for the
    /// debug `AppIconExporter` which renders at 1024 pt and rescales
    /// via `ImageRenderer.scale` for each output size.
    static let canvas: CGFloat = 1024

    var body: some View {
        GeometryReader { geo in
            let side = min(geo.size.width, geo.size.height)
            ZStack {
                background
                highlight
                symbol(side: side)
            }
            .frame(width: side, height: side)
            .clipShape(.rect(cornerRadius: side * 0.2237))
            .frame(width: geo.size.width, height: geo.size.height)
        }
    }

    private var background: some View {
        LinearGradient(
            colors: [
                Color(red: 0.29, green: 0.42, blue: 1.00), // #4A6BFF
                Color(red: 0.69, green: 0.29, blue: 1.00), // #B14AFF
            ],
            startPoint: .topLeading,
            endPoint: .bottomTrailing,
        )
    }

    private var highlight: some View {
        LinearGradient(
            colors: [Color.white.opacity(0.18), Color.white.opacity(0)],
            startPoint: .top,
            endPoint: .bottom,
        )
    }

    private func symbol(side: CGFloat) -> some View {
        Image(systemName: "gauge.medium")
            .resizable()
            .aspectRatio(contentMode: .fit)
            .fontWeight(.semibold)
            .foregroundStyle(.white)
            .frame(width: side * 0.62, height: side * 0.62)
            .shadow(
                color: Color.black.opacity(0.25),
                radius: side * 0.035,
                y: -side * 0.015,
            )
    }
}

#Preview {
    AppIconArtwork()
        .frame(width: 256, height: 256)
        .padding()
}
